### ISSUE TITLE
Crash when TURN server requires credentials

### ISSUE THREAD

**Issue by nebulade** [ionorg/ion#105]
### Your environment.
  - Version: cbd86cd4c700c72ceef2b0848d89dd3f56cf604d
  - Browser: Firefox 75.0b11 (64-bit) Linux and Chromium 80.0.3987.162 

### What did you do?
Joining a conference with two peers. 

### What did you expect?
WebRTC connection to be over TURN

### What happened?
The turn server requires credentials which I couldn't figure out where to specify in the sfu.toml if they are not specified sfu just crashes with
```
2020-04-03 18:47:17.772 ERR NewWebRTCTransport api.NewPeerConnection InvalidAccessError: turn server credentials required
2020-04-03 18:47:17.772 INF rtc.GetOrNewRouter id=8e78b081-ad44-4aea-ac0e-e321eff2abc3#TOUYWG
2020-04-03 18:47:17.773 INF rtc.GetRouter id=8e78b081-ad44-4aea-ac0e-e321eff2abc3#TOUYWG
2020-04-03 18:47:17.773 INF rtc.AddRouter id=8e78b081-ad44-4aea-ac0e-e321eff2abc3#TOUYWG
2020-04-03 18:47:17.774 INF NewRouter id=8e78b081-ad44-4aea-ac0e-e321eff2abc3#TOUYWG
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xe0 pc=0xcc775a]

goroutine 34 [running]:
github.com/pion/ion/pkg/rtc/transport.(*WebRTCTransport).Answer(0x0, 0x1, 0xc000102700, 0x6c6, 0x0, 0xc00038fa20, 0x2b, 0xc000161c00, 0x7f5a04ddd008, 0x0, ...)
	/app/code/pkg/rtc/transport/webrtctransport.go:266 +0x7a
github.com/pion/ion/pkg/node/sfu.publish(0xc00032f6b0, 0x12, 0xc0000e5d90)
	/app/code/pkg/node/sfu/internal.go:88 +0x488
github.com/pion/ion/pkg/node/sfu.handleRequest.func1(0xc00032f680, 0xc00032f740, 0xc00032f770)
	/app/code/pkg/node/sfu/internal.go:31 +0x2f2
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleRequest(0xc00018dc80, 0xc00032f680, 0xc0003379e0, 0x14, 0xc000337a00, 0x19)
	/root/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:150 +0x1d4
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).handleMessage(0xc00018dc80, 0xc0000b8900, 0x820, 0x820, 0xc0003379e0, 0x14, 0xc000337a00, 0x19)
	/root/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:105 +0x156
github.com/cloudwebrtc/nats-protoo.(*NatsProtoo).onRequest(0xc00018dc80, 0xc00036e0a0)
	/root/go/pkg/mod/github.com/cloudwebrtc/nats-protoo@v0.0.0-20200328144814-d3c1c848d442/protoo.go:96 +0x198
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc0000c7b80, 0xc000184240)
	/root/go/pkg/mod/github.com/nats-io/nats.go@v1.9.1/nats.go:2147 +0x330
created by github.com/nats-io/nats%2ego.(*Conn).subscribe
	/root/go/pkg/mod/github.com/nats-io/nats.go@v1.9.1/nats.go:2987 +0x50e
```

The sfu.toml section looks like this:
```
[webrtc]
ice = ["stun:my.nebulon.space:3478", "turn:my.nebulon.space:3478"]
```
Is there a way to specify credentials within that uri schema?
And generally it should maybe nor crash if the server does require credentials.

Thanks!

**Comment by adwpc** [comment]
Thanks！Let me see..

**Comment by adwpc** [comment]
@nebulade Fixed, you can try

**Comment by nebulade** [comment]
Thanks for the quick turnaround. The change fixed the crash, however as far as I understand the very same credentials are now applied to both TURN and STUN servers. At least with the current coturn setup we have, only TURN has credentials, so the STUN requests will fail, since the specified TURN username is not found on the STUN endpoint. Does that make sense or did I misread the changed configuration? Thanks!

**Comment by adwpc** [comment]
> Thanks for the quick turnaround. The change fixed the crash, however as far as I understand the very same credentials are now applied to both TURN and STUN servers. At least with the current coturn setup we have, only TURN has credentials, so the STUN requests will fail, since the specified TURN username is not found on the STUN endpoint. Does that make sense or did I misread the changed configuration? Thanks!

@nebulade fixed..

**Comment by adwpc** [comment]
@nebulade You can try https://github.com/pion/ion/pull/108
