### ISSUE TITLE
docker and docker compose

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#11]
Its looking awesome..

Would be good to have a docker and docker compose for etcd, rabbit MQ, etc.
 Or do you run on k8  or maybe even firecracker ?

**Comment by adwpc** [comment]
Good idea!
But I have no time to do some containerized things.

**Comment by adwpc** [comment]
Add TODO
https://github.com/pion/ion/projects/1#card-29302181

**Comment by winwisely99** [comment]
@adwpc We are on it.
We will push a PR for this and other things

**Comment by maanas** [comment]
@winwisely99 I am also working to add the docker support. 
Work in progress code
https://github.com/minelytics/ion/tree/docker

**Comment by sashaaro** [comment]
@maanas your images looks heavy
and have some excess steps. 
I work on https://github.com/sashaaro/ion/tree/docker
diff https://github.com/pion/ion/compare/master...sashaaro:docker

**Comment by maanas** [comment]
@sashaaro You are right this is just work in progress. I tried to replicate the startup script. I looked at your code. It looks good. I will incorporate the suggestions from your code.

I am not able to establish the connection with two client. I am able to see the local stream, but no connection. Once i am able to get that working, I plan to slim it down and pack it.

**Comment by sashaaro** [comment]
it's work https://github.com/pion/ion/pull/42

**Comment by maanas** [comment]
I tried to build the docker image
I am getting this error
> ion_1       | 2020-02-22 02:15:12.670677 I | http: TLS handshake error from 172.21.0.1:33272: remote error: tls: bad certificate

The web app is stuck at waiting for other people joining

**Comment by sashaaro** [comment]
It is done. https://github.com/pion/ion/pull/42 was merged already. We can close this issue.
