### ISSUE TITLE
build.sh doesn't build cmd/sfu

### ISSUE THREAD

**Issue by luto** [ionorg/ion#112]
### Your environment.
  - Version: b9766adcfa36caa17402a90066a8fc6af827804e / master
  - Browser: N/A

### What did you do?

run `scripts/build.sh` on master.

### What did you expect?

all components of ion (biz, islb, sfu) are built.

### What happened?

only biz and islb are built. sfu isn't.

**Comment by adwpc** [comment]
fixed.

**Comment by luto** [comment]
Thanks!

**Comment by luto** [comment]
Thanks for the quick fix, but the build fails for me with

> go: extracting github.com/klauspost/cpuid v1.2.3
> verifying github.com/tjfoc/gmsm@v1.3.0: checksum mismatch
>	downloaded: h1:qhgkrZru95jFP9NbVPknJvc9vgkMXhOEzkOASKdc0oQ=
>	go.sum:     h1:i7c6Za/IlgBvnGxYpfD7L3TGuaS+v6oGcgq+J9/ecEA=
>
> SECURITY ERROR
> This download does NOT match an earlier download recorded in go.sum.
> The bits may have been replaced on the origin server, or an attacker may
> have intercepted the download attempt.

during the new `go build -o /ion/bin/sfu` step on a clean CentOS 7. Considering `go.sum` comes from within the git repo: does it need an update? Just deleting the file seems to "resolve" the issue, but I am not sure that's the way to go.

This can be reproduced inside `docker run  -ti centos:7`:

```
yum install epel-release -y
yum install golang -y
git clone https://github.com/pion/ion.git
cd ion/
./scripts/build.sh 
```

@adwpc I am not a go dev myself. Do you have any tips on how to resolve this properly?

**Comment by adwpc** [comment]
@luto try
export GOPROXY=https://goproxy.io

**Comment by luto** [comment]
Setting `GOPROXY` fixes the issue. Thank you!
