### ISSUE TITLE
ion-sfu crashes when a 2nd client connects to a room

### ISSUE THREAD

**Issue by luto** [ionorg/ion#114]
### Your environment.
  - Version: 3028e6bf4e1cfbca787271b9adfdd3455904720c
  - Browser: Chrome 80

#111 exhibits a similar behavior, but prints a different error message.

### What did you do?

1. build ion using `srcipts/build.sh`
2. build frontend using `cd sdk/js; npm i; cd demo; npm i; npm run-script build`
3. serve `sdk/js/demo/dist` using nginx
4. open ion in chrome
5. open ion in incognito chrome

`sfu.toml` modifications, taken von `docker/sfu.toml`:

```
[webrtc]
# Range of ports that ion accepts WebRTC traffic on
portrange = [43061, 43063]
[webrtc.iceserver]
urls = ["stun:stun.l.google.com:19302"]
```

All other config is like in `configs`.

### What happened?

ion-sfu crashes when a 2nd client connects to a room

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc4434f]

goroutine 1543 [running]:
github.com/pion/ice.closeConnAndLog(0x0, 0x0, 0x10b8cc0, 0xc0002389c0, 0xc000aba140, 0x38)
	/home/ion4/go/pkg/mod/github.com/pion/ice@v0.7.10/gather.go:26 +0x5f
github.com/pion/ice.(*Agent).gatherCandidatesSrflx.func1(0xc00049ffa0, 0xc0004706c0, 0x1, 0xc000140405, 0x11, 0x4b66, 0x0, 0x0, 0x0, 0x0, ...)
	/home/ion4/go/pkg/mod/github.com/pion/ice@v0.7.10/gather.go:239 +0x4dd
created by github.com/pion/ice.(*Agent).gatherCandidatesSrflx
	/home/ion4/go/pkg/mod/github.com/pion/ice@v0.7.10/gather.go:228 +0x187
```

[sfu-debug.log](https://github.com/pion/ion/files/4452027/sfu-debug.log)

If there is any additional information I can provide, please tell me. I am also happy try patches in a timely manner.

Thanks for any help!

**Comment by adwpc** [comment]
Fixed
Your port range too small

**Comment by luto** [comment]
oh, I see. What is the recommended minimum size?

**Comment by adwpc** [comment]
> oh, I see. What is the recommended minimum size?

I think it should be bigger than 100 to support many clients
