### ISSUE TITLE
auto build and upload images to Dockerhub

### ISSUE THREAD

**Issue by Sean-Der** [ionorg/ion#119]
I don't know what this looks like yet, but we really need to do this. Right now images can fall out of date, and the drift between this repo and the images causes confusion. I can take on the dev work, but just want to make sure I don't make any mistakes. 

I need to look for prior art with other projects, maybe we can always auto-push latest. But then we should setup something to tag+build for us?

**Comment by Sean-Der** [comment]
@tarrencev any opinions?

**Comment by tarrencev** [comment]
I agree this would be super helpful. Seems like dockerhub supports building from source https://docs.docker.com/docker-hub/builds/. Maybe that is straightforward to get up and running?

**Comment by tarrencev** [comment]
Added docker build/push travis job for `latest` tags when pushing to master in #197

**Comment by tarrencev** [comment]
Done!
