### ISSUE TITLE
Use NATS instead of rabbit

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#12]
I am thinking about providing a NATS streaming OR Lift Bridge MQ to match your interface.

https://github.com/liftbridge-io/liftbridge

But i am raising this first because i want to get an idea of the intended patterns for MQ that your using first.

**Comment by adwpc** [comment]
I have not used NATS before.
I use rabbitmq for non-blocked rpc-calling and broadcasting

**Comment by adwpc** [comment]
Add TODO
https://github.com/pion/ion/projects/1

**Comment by gedw99** [comment]
https://blog.greta.io/a-signaling-system-for-10m-concurrent-connections-10d327fd6837

NATS versus rabbit

**Comment by adwpc** [comment]
Aswsome！Thanks！

**Comment by winwisely99** [comment]
Liftbridge, a kafka replacement is now ready too
https://github.com/liftbridge-io/liftbridge

its the more simpler nats. and is just like kafka

**Comment by maanas** [comment]
@winwisely99 
NATS sounds promising and it has a go client too.
