### ISSUE TITLE
Adding/Removing tracks from stream

### ISSUE THREAD

**Issue by tarrencev** [ionorg/ion#120]
I'm playing around with adding/removing tracks from an existing streams and i think either we are not handling things properly or i misunderstand the functionality. If i open a stream with video/audio, mute audio (remove the track), then unmute (add the track back), the Ion server correctly handles the track update but other clients do not. Should the SFU implement some logic to call the `ontrack` handler on the client peer connection when tracks are add/removed from a stream?

**Comment by adwpc** [comment]
Did you mean the pub works well when you addtrack/removetrack on the client；And the sub is not ok？

**Comment by tarrencev** [comment]
yes exactly, when pub removes/adds a track, sub is not updated

**Comment by GQAdonis** [comment]
I have observed this behavior as well.  In fact, there are times when a user inserts or reinserts themselves into a session and their presence is not immediately known to all the other peers.  As a result, that new person can see and hear everyone else, but none of the original members of a session can see or hear that person (or even know that he has been added).
