### ISSUE TITLE
Don't mark users as joined until they have passed ICE

### ISSUE THREAD

**Issue by Sean-Der** [ionorg/ion#122]
Don't know how possible this is, but we are getting lots of bug reports where users are confused why they are in a room but can't see each other.

![Screen Shot 2020-04-14 at 23 46 07](https://user-images.githubusercontent.com/1302304/79306496-2a73e580-7eaa-11ea-98f6-8ee3f07f2644.png)

**Comment by GQAdonis** [comment]
DITTO!  I am looking into this myself.
