### ISSUE TITLE
Persistent "Wait for other people joining ..." and no camera options

### ISSUE THREAD

**Issue by pmalek** [ionorg/ion#124]
### Your environment.
  - Version: https://github.com/pion/ion/commit/4e74cd3c0ab426ecca4570f13ced16ce4535ea65
  - Browser: `Firefox 76.0b5 (64-bit)` (also tried on `Chrome Version 83.0.4103.14 (Official Build) beta (64-bit)`)

### What did you do?
```
docker-compose pull
docker-compose up
# go to http://localhost:8080
```

### What did you expect?
To see my camera view, to see chat, to see camera options

### What happened?
Blank camera options 

![image](https://user-images.githubusercontent.com/739996/79552923-024bd880-809c-11ea-91e3-74972c35e604.png)

and a persistent `Wait for other people joining ...` even if joined from another window.

**Comment by funvit** [comment]
Same on Chrome 80.0.3987.163 on macos.

Msg in console:

```
The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu

Uncaught (in promise) TypeError: Cannot read property 'enumerateDevices' of undefined
    at index.js:73
```

**Comment by jeremija** [comment]
Browsers won't allow access to media devices when using plain HTTP (and a hostname other than localhost). HTTPS needs to be enabled. I haven't used pion/ion before, but you'll need to generate a self-signed certificate and configure it to use a self-signed certificate for testing.

**Comment by adwpc** [comment]
Make a list here
#152
