### ISSUE TITLE
InvalidAccessError: Answer tried to set recv when offer did not set send

### ISSUE THREAD

**Issue by kngako** [ionorg/ion#127]
### Your environment.
  - Version: 4e74cd3
  - Browser: Firefox 75.0 (64-bit)
  - Other Information - Ubuntu 18.0.4*stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?
Opened a room on 1 device using firefox. And went into that room from a different device using chrome.

### What did you expect?

The two devices would stream to each other.

### What happened?

The firefox device didn't recieve the stream from the chrome device with the error. **InvalidAccessError: Answer tried to set recv when offer did not set send**. I could successfully see the stream from the Firefox device on the chrome device.

The error gets thrown on line 142.

https://github.com/pion/ion/blob/4e74cd3c0ab426ecca4570f13ced16ce4535ea65/sdk/js/src/Client.js#L134-L144

**Comment by kngako** [comment]
Dupe #126

**Comment by adwpc** [comment]
Make a list here:
#152
