### ISSUE TITLE
k8s hosted support

### ISSUE THREAD

**Issue by firaskafri** [ionorg/ion#128]
failed to copy buffer: readfrom tcp 10.244.0.79:45390->10.244.2.17:8443: use of closed network connection

### Your environment.
  - Version: 0.10
  - Browser: Edge
  - Other Information - failed to copy buffer: readfrom tcp 10.244.0.79:45390->10.244.2.17:8443: use of closed network connection

**Comment by adwpc** [comment]
Browser: Edge? 
We didn't test this browser before.
where does the error log come from ?

**Comment by adwpc** [comment]
Please use chrome to test.
