### ISSUE TITLE
Documentation beyond basic setup?

### ISSUE THREAD

**Issue by wicknet** [ionorg/ion#129]
Installed on Ubuntu 18.04 running Docker CE and compose, with the bare instructions on the project page. Beyond that, there doesn't seem to be any documentation available - in the knowledge base or faq's. 

At the minimum, the developers should consider adding clear instructions on how to enable proper https (without using non-standard ports), adding LetsEncrypt certs, clarifying which ports need to be opened on the network firewall, and adding authentication so anyone with the server's fqdn or iP cannot simply login and start using the service.

For inspiration, please check-out more mature projects like Jitsi and Big Blue Button. 

Thanks!

**Comment by adwpc** [comment]
Thanks for your advise！
https://github.com/pion/ion/wiki/4.-Develop-and-Debug
We working on this
