### ISSUE TITLE
Audio Level Detection

### ISSUE THREAD

**Issue by tarrencev** [ionorg/ion#130]
I am interesting in adding audio level detection for stream prioritization. I'd like to use RTP header extensions to extract this information according to https://tools.ietf.org/html/rfc6464. I would like to implement this as a router extension. We can handle toggling video quality based on the active speaker.

I'm working on understanding what is necessary to add this functionality. It doesnt seem that pion parses these headers today (looking at https://github.com/pion/rtp/). But i do see AudioLevel in the stats package here:
https://github.com/pion/webrtc/blob/93261960b1c10359cfeef337a0710c4b0ce3c8a6/stats.go#L704

Is my understanding correct that we need to first implement the header parsing in the rtp package or is it possible to use the existing stats package? Any other insights appreciated too :)

**Comment by adwpc** [comment]
Yep, maybe you should add this feature in pion first

**Comment by tarrencev** [comment]
Added extension support in https://github.com/pion/rtp/pull/55

**Comment by grahamking** [comment]
These two PRs make ion-sfu negotiate that extension:
 - https://github.com/pion/sdp/pull/94
 - https://github.com/pion/ion-sfu/pull/373 (depends on the above)

**Comment by adwpc** [comment]
will support in #546
