### ISSUE TITLE
Maybe suggest what ion can do and what ion cannot do in the readme

### ISSUE THREAD

**Issue by khainhero** [ionorg/ion#134]
Hey guys, 

I am a bit confused and maybe a small edit to the readme can help others in the future(noobs like me!)

**How can i block users from creating rooms but only allow them to join?** Can i move or split the creation of 'room' versus the current 'join'. I already have my own list of authenticated users.

Because wouldn't anyone who knows my SFU media server https url now will be able to build their own apps but use my url? (**how to prevent potential abuse**)

Is this just a SFU media server which we can self host? 

**Does it include its own TURN which is used by our host server?**

**Do we really need a turn signal to connect peers to the SFU media server?** 

What if I hosted this docker container to my google compute instance or digitalOcean, if a user cannot connect to my compute instance because of their personal firewall etc, I am fine if they cannot connect because that would mean that rest of my app is blocked as well. 

**Is this the right kind of thinking?**

Thank you so much and please stay safe.

**Comment by adwpc** [comment]
https://github.com/pion/ion/wiki/6.-Q&A
added

**Comment by khainhero** [comment]
wonderful thank you

that was quick :)
