### ISSUE TITLE
SFU crashes when larger numbers of people join

### ISSUE THREAD

**Issue by barronbud** [ionorg/ion#135]
### Your environment.
  - Version: *e610a1cc1a77af2542b5b82bb412632204840f8f*
  - Browser: *Chrome 81.0.4044.113 on macOS 10.15.4* (But variety of OSes and Browser versions)
  - Running on AWS Lightsail instance - Debian 9.5 | 4GB RAM | 2 vCPUs

### What happened?
1. Create and join room
1. Get over 10 attendees to join (with a 1s delay on each join)
    * We are using a Selenium script to spawn multiple attendees with automated activity, but have the same results with human interaction. (See https://github.com/pion/ion/pull/136 for script)
1. All attendees are ejected from room, streams are terminated, and unable to re-enter the room
1. SFU container has crashed and is no longer running, requiring restart of the container

This only seems to occur at higher numbers of attendees and not in rooms with 2-6 people, where the performance is as expected.

### Logs
Initial indications of issues in the logs are:
```
[biz_1] 2020-04-23T15:04:21Z WRN Got error: websocket: close 1006 (abnormal closure): unexpected EOF
[biz_1] 2020-04-23T15:04:21Z WRN Transport got error (1006, unexpected EOF)
[biz_1] 2020-04-23 15:04:21.538 INF signal.in handleClose [1006] unexpected EOF rooms=[0xc0000ead20]
```
It appears that once the websocket crashes, Ion repeatedly tries to renegotiate the streams, causing SFU to get swarmed with ICE renegotiations. Without the messaging on the websocket, there doesn't seem to be anything throttling it, eventually causing SFU to crash.

Eventually we see this panic:
```
[sfu_1] 2020-04-23 16:59:59.004 INF subscribe tracks=map[vzWuPTiVrCEiyI25RZP2SQNHZCw1UxkekcsK 865738ef-cdea-4e95-9d70-8450cbaea159:[map[codec:OPUS fmtp: id:865738ef-cdea-4e95-9d70-8450cbaea159 pt:111 ssrc:1.210567037e+09 type:audio]] vzWuPTiVrCEiyI25RZP2SQNHZCw1UxkekcsK 970e68d2-4f74-44e9-afe9-368c902a2123:[map[codec:VP8 fmtp: id:970e68d2-4f74-44e9-afe9-368c902a2123 pt:96 ssrc:1.933384069e+09 type:video]]]
[sfu_1] panic: runtime error: invalid memory address or nil pointer dereference
[sfu_1] [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc32d1f]
[sfu_1] 
[sfu_1] goroutine 199512 [running]:
[sfu_1] github.com/pion/ice.closeConnAndLog(0x0, 0x0, 0x10b0000, 0xc0020ac9c0, 0xc0071728c0, 0x39)
[sfu_1] 	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:26 +0x5f
[sfu_1] github.com/pion/ice.(*Agent).gatherCandidatesSrflx.func1(0xc005f62c90, 0xc00684ef00, 0x1, 0xc000034425, 0x11, 0x4b66, 0x0, 0x0, 0x0, 0x0, ...)
[sfu_1] 	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:260 +0x4f3
[sfu_1] created by github.com/pion/ice.(*Agent).gatherCandidatesSrflx
[sfu_1] 	/go/pkg/mod/github.com/pion/ice@v0.7.12/gather.go:249 +0x189
```
Full Log File: 
[pion-log4.tar.gz](https://github.com/pion/ion/files/4530344/pion-log4.tar.gz)

**Comment by adwpc** [comment]
Thanks！This can fix
https://github.com/pion/ice/pull/170
