### ISSUE TITLE
While testing the demo app, I get error

### ISSUE THREAD

**Issue by rajababu3** [ionorg/ion#139]
### Your environment.
  - Version: latest, used git clone
  - Browser: chrome lastest
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

I tried the demo app and it shows waiting for the peer to join but in the notification dialog, it shows Peer Joined - "Raja" 

So, I am not receiving a video element. It is weird that sometimes it works and sometimes it does not.

### What did you expect?
Can you guide me? 
- I followed the basic documentation. 
- docker-compose up

**Comment by rajababu3** [comment]
After restarting the server this issue is gone. 

Is this the expected behavior?

**Comment by adwpc** [comment]
No
You can paste logs/xxx.log   or  chrome console log  if you find this error again.

**Comment by adwpc** [comment]
try new docker image
