### ISSUE TITLE
did not receive the video stream

### ISSUE THREAD

**Issue by zhuwei** [ionorg/ion#14]
After I ran the project successfully, both clients joined the room1 at the same time, but they did not receive the video stream from each other. why？please help me，thank you very much！

**Comment by zhuwei** [comment]
Unable to trigger this event:
sdk/js/src/SFU.js=>onRtcCreateRecver

**Comment by zhuwei** [comment]
No open partial port.
Which ports need to be open?

**Comment by adwpc** [comment]
Make sure all the modules installed and start up successful，see scripts folder

**Comment by adwpc** [comment]
Thanks for using ion，will make it better

**Comment by zhuwei** [comment]
@adwpc Thank you very much！

**Comment by Sean-Der** [comment]
@adwpc `ion` is amazing, I have learned a lot from reading your code/documents so far :)

@zhuwei thanks for using it! reports are awesome, helps everyone get better
