### ISSUE TITLE
macos deploy get this Cannot start service web: Ports are not available errror 

### ISSUE THREAD

**Issue by lsdlab** [ionorg/ion#141]
### Your environment.
  macos 10.13

### What did you do?

docker-compose pull success and then docker-compose up

![image](https://user-images.githubusercontent.com/8236988/80333692-81ea5c00-8881-11ea-8274-078bb1f01bc4.png)

### What did you expect?

running local deploy

### What happened?

i reset my mac docker, and it's still get this error, i didn't start and services using 80 port

**Comment by tarrencev** [comment]
Seems like something is already bound to a required port. 

The docker-compose binds:

```
      - 80:80
      - 8080:8080
      - 8443:8443
```

Can you check that those aren't allocated?

You can do `lsof -nP -iTCP:$PORT | grep LISTEN`

**Comment by fmaker** [comment]
For me it is port 5060 with ion_sfu_1:
`CommCente 11605 fmaker   26u  IPv6 0x18322b1c9e05e853      0t0  TCP [2607:fb90:13c2:d442:3ba0:2a33:6646:80f0]:5060 (LISTEN)`

It is the [Apple CommCenter service](https://www.theiphonewiki.com/wiki//System/Library/Frameworks/CoreTelephony.Framework/Support/CommCenter) used for displaying text messages from your iOS device, among other things.

**Comment by adwpc** [comment]
You can check your port

**Comment by fmaker** [comment]
Why can't we make the port configurable? I can't disable or move the service that is using the port.

**Comment by tarrencev** [comment]
Ports are configurable. https://github.com/pion/ion/blob/master/configs/sfu.toml#L29
