### ISSUE TITLE
SFU crash on fatal error: concurrent map iteration and map write

### ISSUE THREAD

**Issue by barronbud** [ionorg/ion#144]
### Your environment.
  - Version: *6c7527c068cc0f826e1bdef7657f387fefaa4622*
  - Browser: *Chrome 81.0.4044.122 on macOS*
  - Other Information - *occurred with more than ten clients (two of which were Firefox)*

### What happened?
1. Created room
1. Invited more than 10 people - 2 initially joined with Firefox
1. After a certain point, the SFU container crashed with following error:
```
[sfu_1] 2020-04-27 16:32:28.304 ERR WebRTCTransport.WriteRTP track==nil pkt.SSRC=1047152335
[sfu_1] 2020-04-27 16:32:28.304 ERR wt.WriteRTP err=track is nil
[sfu_1] 2020-04-27 16:32:28.304 INF Router.jitter r.GetPub().WriteRTCP PictureLossIndication 3e7b5004 3e7b5004
[sfu_1] 2020-04-27 16:32:28.304 INF Router.jitter r.GetPub().WriteRTCP PictureLossIndication 95c90643 95c90643
[sfu_1] 2020-04-27 16:32:28.305 INF AddTrack: codec:OPUS, ssrc:3374338654, pt:111, streamID Vlwwynlj80IWrPNGUU2ko8ruPpQnbRklv9ME, trackID 403631d1-a413-4cca-b57e-12e63b850a91
[sfu_1] 2020-04-27 16:32:28.305 INF AddTrack: codec:VP8, ssrc:1855654096, pt:96, streamID Vlwwynlj80IWrPNGUU2ko8ruPpQnbRklv9ME, trackID c40933a8-aec7-43d8-b9ad-b33515540cb2
[sfu_1] 2020-04-27 16:32:28.306 INF Router.AddSub id=b3927b95-c1bf-4886-87c1-99ce5c722d42#YRDNYY t=0xc0361e70e0
[sfu_1] fatal error: concurrent map iteration and map write
```
After the fatal error, a stream of stack traces was written to the log: 
[pion-crash-stacktrace.log](https://github.com/pion/ion/files/4541820/pion-crash-stacktrace.log)

Note: _The full log has over 137,000 lines of the "track is nil" error, which I believe are traceable to the two Firefox clients._

**Comment by adwpc** [comment]
This is because too many logs printing
https://github.com/pion/ion/commit/e6b1d204bac40fa9ca65942b60de6aeb3380ebf6 fixed
Please use chrome.
