### ISSUE TITLE
wss is not support?

### ISSUE THREAD

**Issue by zhuwei** [ionorg/ion#15]
`
I/flutter (17295): [protoo-client] DEBUG: emit "error" [currentAttempt:HandshakeException: Handshake error in client (OS Error:
I/flutter (17295): 	CERTIFICATE_VERIFY_FAILED: self signed certificate(handshake.cc:352))]
`

**Comment by adwpc** [comment]
@cloudwebrtc can help

**Comment by cloudwebrtc** [comment]
Solved. https://github.com/cloudwebrtc/dart-protoo-client/issues/1
