### ISSUE TITLE
Caddy v1 is outdated docker

### ISSUE THREAD

**Issue by dhruvil2111** [ionorg/ion#151]
Caddy v1 is outdated can you help to setup with caddy 2 in docker

**Comment by jbrady42** [comment]
This was updated in #143 which was merged, but reverted recently. Stay tuned for updates on when these land in master.

**Comment by adwpc** [comment]
Some problems have not been solved..

**Comment by adwpc** [comment]
update to v2

**Comment by dhruvil2111** [comment]
awesome thanks
