### ISSUE TITLE
Package clients in separate repo

### ISSUE THREAD

**Issue by tarrencev** [ionorg/ion#157]
Since the Ion package is gaining more traction, I think it would be better to extract the flutter/js clients/sdks to a separate repo. That way this can be focused on the core framework and we can have another repo focused on frontend. Since they require different skillsets to contribute i think it would make that process easier too. Just an idea :)

**Comment by adwpc** [comment]
Thanks！
This is exactly what we want to do next：）

**Comment by adwpc** [comment]
flutter sdk has been moved to:
https://github.com/pion/ion-sdk-flutter

**Comment by tarrencev** [comment]
published the js sdk to https://github.com/pion/ion-sdk-js

**Comment by jbrady42** [comment]
What is the plan for the js demo app. Is that moving to a separate repo as well?

**Comment by adwpc** [comment]
Maybe a new repo ion-web
