### ISSUE TITLE
Q&A: 4.Does it include its own TURN which is used by our host server?

### ISSUE THREAD

**Issue by nvcnvn** [ionorg/ion#161]
https://github.com/pion/ion/wiki/6.-Q&A#4does-it-include-its-own-turn-which-is-used-by-our-host-server

The answer in wiki say "No"

But in https://github.com/pion/webrtc/issues/9 Beyond Heretic -- 2.1.0 (2019-08-00)
Say we have TURN sever.

What is this mean?

**Comment by adwpc** [comment]
It means:
ion doesn't have it's own turn server
you can choose one or build yourself
you can use this package to build
https://github.com/pion/turn
