### ISSUE TITLE
Sub not clean when sub leave room

### ISSUE THREAD

**Issue by adwpc** [ionorg/ion#163]
pub: dc1/loadtester/gSVfSlp9DTBL/media/pub/715ecbbc-4b5b-411a-bf08-8203e573777a#KXSQDK
subs: 2

subs not reduce when they leave room

**Comment by generalomosco** [comment]
same issue here

**Comment by tarrencev** [comment]
@jbrady42 fixed in #220?

**Comment by jbrady42** [comment]
Yes, but I have since learned we should be hooking the ICE failed state for shutdown and not disconnected because it could be temporary.
