### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by HathTech** [ionorg/ion#164]
### Your environment.
  - Version: latest
  - Browser: chrome
  - Other Information - None

### What did you do?

git clone  <GIT_LINK>
added env variables 

### What did you expect?
When I access the domain it says ERR_SSL_PROTOCOL_ERROR

**Comment by HathTech** [comment]
Change the documentation, please. 
The Master branch has lots of issues. 
Ask the developers to get the release version if you are using it for production.

**Comment by adwpc** [comment]
Thank for your advise :)
v0.3.0 worked.
