### ISSUE TITLE
It is not okay for client to notify server before doing clean up

### ISSUE THREAD

**Issue by generalomosco** [ionorg/ion#168]
It is not okay for client to notify server before doing clean up of stream and broadcasting stream removed or participant left notification to other participants in the room.
server can aware on socket connection closed

**Comment by generalomosco** [comment]
Because it is a big issue thereby resending stream of participant that left the room without notifying server

**Comment by generalomosco** [comment]
As soon i added on peer close function event to AddPeer, so to my unexpectation it started emitting leave and stream clean up when user left. because i was suspecting [L45](https://github.com/cloudwebrtc/go-protoo/blob/master/room/room.go#L45) the event there already deleted the peer before ion handleClose later trying to GetRoomsByPeer [L74](https://github.com/pion/ion/blob/master/pkg/signal/handle.go#L71)

so i added empty peer.On("close"... [L13](https://github.com/pion/ion/blob/master/pkg/signal/room.go#L13  )with only log and it worked, i don't know!  i  was wanting to do the logic in the event instead 
```
 func (r *Room) AddPeer(peer *Peer) {
  peer.On("close", func(code int, err string) {
	})
	r.Room.AddPeer(&peer.Peer)
  peer.Peer.On("close", func(code int, err string) {
	})
}
```

**Comment by tarrencev** [comment]
Closing since i think this is the same as #163. Please discuss there.
