### ISSUE TITLE
is it possible to record video conferencing in server side?

### ISSUE THREAD

**Issue by eleomilagrosa** [ionorg/ion#177]
is it possible to record video conferencing in server side?

when a "Record" button is pressed, the room will start recording.
it will only stop recording when "Stop" button is pressed or there's no one in the room anymore.

I tried digging in the source code of ion, 
this is the only thing related i found.
https://github.com/pion/webrtc/blob/master/examples/save-to-disk/main.go#L97

but I think this code will always record the connection. 
I hope it is possible to selective recording.

I hope to use it in flutter.

any help will be appreciated

**Comment by tarrencev** [comment]
This is not supported yet. We have a webm saver plugin but it still needs some work. It doesn't support conditional recording either. It is either enabled/disabled by config during initialization. If you are interested in working on this, that would be great!

**Comment by tarrencev** [comment]
supported by avp now

**Comment by eleomilagrosa** [comment]
Thanks 👍 
it is really great hearing this news

can you elaborate more?
so conditional recording is now supported?

can you put a link or any hint how to make this work?
or which file it is now?

is it now available in Flutter demo too?

**Comment by ssadok** [comment]
can you write the link of the commit please ?

**Comment by nntwelve** [comment]
Currently the ion project does not use avp, so can u give me some documentation for recording in server, please?? thanks
