### ISSUE TITLE
Flutter Web

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#19]
I noticed that React web is in the SDK for web in this repo.

There is already a demo here using Flutter web: https://github.com/cloudwebrtc/flutter-webrtc-demo/tree/master/web
I have not tried it yet though. I have only tried the Mobile and desktop.

Is there any interest in getting ion working working with Flutter Web ?

Protobufs can designed to work fine with Flutter Web and golang over websockets for the required signalling.

My intention is to get Video channels and Data channels working with ION to enable PUB SUB architectural patterns.

Please let me know what the project intentions are and if this is something that we can work towards together.

**Comment by cloudwebrtc** [comment]
@winwisely99 Good idea, Flutter Web will be supported in ion-flutter-sdk. The reason for using ion-js-sdk and React.js is because we have to take care of most users who develop web apps using traditional js, so ion client SDK Will support both js and flutter.

**Comment by winwisely99** [comment]
thank you for the feedback.
