### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by angelorc** [ionorg/ion#232]
Hello,
its Angelo from BitSong.

I'm currently building a new blockchain based on tendermint/cosmos-sdk. BitSong is born to create a new blockchain for contents and streaming.

Next week I will publish the sdp module into our blockchain and we will start some internal test.
With sdp module an account can publish their offer/answer.
Our blockchain have a 5s blocktime so users dont need to wait long time.

I'm texting you to know if you are interested to collaborate with us and build something awesome and amazing.
Also I'm accepting advice about webrtc, example if can be an other important component like SDP to be integrated into our blockchain.

Waiting for your reply
Angelo
Telegram: @bitangel84
https://bitsong.io

**Comment by tarrencev** [comment]
Sounds like an interesting project. You are welcome to use Ion and we would love any contributions. I'm not sure exactly how Ion could integrate with Bitsong. Today SDP negotiation is already trustless so i'm not exactly sure what doing it on a blockchain would enable? Excited to hear more.

**Comment by angelorc** [comment]
To use SDP you need a third-party the offer/accept.

Thanks to the sdp module on bitsong, two account can publish their information about the sdp and then the blockchain can be used to updates clients/accounts or connected services.

Example I want to create a media server for bitaong app, but also I want to decentralize the media server and give other users the possibility to rent their computational to the account that need a microservice to go live.

Also you can use the subscriptiom module, it mean that if one of my services are used to stream content the blockchain will send the cost of the subscription at each block.

Also (but Im not sure), one more modules could be for stun/turn, to avoid the centralization we can use the blockchain to update the informations

**Comment by tarrencev** [comment]
Interesting! Looking forward to it. Let us know if you have any issues working with Ion.
