### ISSUE TITLE
Manifest Error

### ISSUE THREAD

**Issue by meftunca** [ionorg/ion#238]
```bash
docker-compose up // or pull
```

Command results:
```
ERROR: for avp  manifest for pionwebrtc/ion-avp:0.2.0 not found: manifest unknown: manifest unknown
ERROR: manifest for pionwebrtc/ion-avp:0.2.0 not found: manifest unknown: manifest unknown
```

**Comment by itechbg** [comment]
same issue here.

docker-compose pull
Pulling nats  ... done
Pulling etcd  ... done
**Pulling avp   ... error**
Pulling biz   ... done
Pulling sfu   ... done
Pulling redis ... done
Pulling islb  ... done


Pulling avp (pionwebrtc/ion-avp:0.2.0)...
ERROR: manifest for pionwebrtc/ion-avp:0.2.0 not found: manifest unknown: manifest unknown

**Comment by roger254** [comment]
![Screenshot (11)](https://user-images.githubusercontent.com/26280809/82850024-5cde1d00-9f03-11ea-952f-b112005961cd.png)
same here

**Comment by tarrencev** [comment]
for now you can use the 'latest' tag. we will push an updated tag for avp tomorrow

**Comment by tarrencev** [comment]
You should be able to run successfully with `docker-compose.stable.yml` now.
