### ISSUE TITLE
No remote feed on FireFox

### ISSUE THREAD

**Issue by GQAdonis** [ionorg/ion#245]
### Your environment.
  - Version: Commit 490837a9ff7e570e430958691317dd86fc9c7595 (latest)
  - Browser: *FireFox 76.0.1 (Mac) and FireFox 76.0.1 (Windows 10)*
  

### What did you do?
I updated the code base on my Linux server in DigitalOcean and manually rebuilt all the Docker images locally from source.  

Next, I restarted the Docker VM's with the new code and tried to start sessions involving the two types of FireFox browsers.

### What did you expect?

I expected to see both the local and remote video and audio tracks for the session.

### What happened?

On. FireFox, I only saw the local video.  On Chrome for the second participant, I saw messages related to a new stream appearing but never saw the FireFox browser stream.

The behavior is the same whether the Chrome browser starts the session or the FireFox browser.

When using only FireFox browsers, only local streams appear on each.

**Comment by jbrady42** [comment]
Firefox support was just added and there are still a few kinks to work out. What codecs were you using from both sides. Also can you see if there were any abnormal log lines from sfu?

**Comment by jbrady42** [comment]
Currently VP9 seems to be the best supported between the two.
