### ISSUE TITLE
[Documentation] Any pointers on how to run this behind an Nginx reverse proxy?

### ISSUE THREAD

**Issue by helkaluin** [ionorg/ion#254]
I would guess 5000-5200/udp needs to be opened to WAN, are there any other public-facing ports?

From https://github.com/pion/ion-app-web/ I suppose I should `npm install` and then `npm run build`. Nginx should then point /ws to localhost:8443 with `proxy_set_header Upgrade $http_upgrade; proxy_set_header Connection $connection_upgrade;`. Am I missing anything?

**Comment by adwpc** [comment]
https://github.com/pion/ion-app-web/wiki/DeployByNginx

UDP:5000-5200
TCP:8080
