### ISSUE TITLE
 How to push RTMP to sfu?

### ISSUE THREAD

**Issue by liping17** [ionorg/ion#267]
According to the architecture diagram, RTMP can be accessed

**Comment by adwpc** [comment]
This is planning feature

**Comment by Sean-Der** [comment]
@liping17 I have a RTMP Servers that makes inputs available via WebRTC [here](https://github.com/Sean-Der/rtmp-to-webrtc)

I am going to integrate this into ion soon! When a few architectural bits fall into place I will do this :)
