### ISSUE TITLE
error docker compose

### ISSUE THREAD

**Issue by masatrio-business-account** [ionorg/ion#268]
sfu_1    | config file /configs/sfu.toml loaded failed. 1 error(s) decoding:
sfu_1    | 
sfu_1    | * 'plugins.jitterbuffer' has invalid keys: tccon
sfu_1    | Usage:/usr/local/bin/sfu {params}
sfu_1    |       -c {config file}
sfu_1    |       -h (show help info)

**Comment by tarrencev** [comment]
cutting a new release now. you can use the default `docker-compose.yml` in the mean time

**Comment by tarrencev** [comment]
should be fixed now!
