### ISSUE TITLE
Play a video from Youtube

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#30]
We are using Ion in Fluttter Web and Mobile.

I was wondering if it would be possible to leverage ion to play normal streaming videos that are hosted on a server OR embedded in the app as Flutter Assets ?

If they are flutter assets then they woudl need to be pre-transcoded for ion i guess ?

If hey were from Youtube ( for example ) then the ion server could transcode them on the fly ?

**Comment by cloudwebrtc** [comment]
I think we have to take a look first, how is the YouTube video stream transmitted outwards, RTMP or HLS or Dash? Then collected by an ion client, published to the ion channel.
@adwpc

**Comment by winwisely99** [comment]
Proposal:

We transcode all videos beforehand on our servers. We would use a golang lib to do this. 

https://github.com/rylio/ytdl

https://github.com/iawia002/annie

Then to convert it to a format that Webrtc accepts we would use the pion media libs.

For  Desktop or Mobile we can do this in the Background Service that is written in golang.
For Web, the Server would do it.

**Comment by winwisely99** [comment]
https://github.com/rylio/ytdl works great. i just tried it.

**Comment by winwisely99** [comment]
This plays an MP4 ( like that is download above) in Webrtc
https://golangexample.com/watch-videos-with-friends-using-webrtc/
