### ISSUE TITLE
PORT & Deployment

### ISSUE THREAD

**Issue by masatrio-business-account** [ionorg/ion#302]
how exactly each service communicate each other?

and is it okay if i changed pprof or expose port?

**Comment by leewardbound** [comment]
SFU, ISLB, AVP and BIZ mostly interact with each other using NATS as a messaging queue and `etcd` for service registration. ISLB also uses `redis` internally as a routing cache (I think).

PProf is a profiling helper for development and not necessary in production; you can disable it in the config.toml for each service, and if you do leave it enabled you should ensure the port isn't accessible. Also I think `docker-compose` is the most common/advised way to run the services, so if you don't expose the pprof ports on the docker containers, nobody can access it.

The only service that needs an outside port for `ion` is `biz:8443` which is a websocket signal interface for sending `join()` and `publish()` and `subscribe()` messages, basically. If you are running `ion-app-web` also via docker (recommended) as a web UI, you should keep `biz:8443` private and expose `ion-app-web` (it's a Caddy reverse proxy) over port `443` for HTTPS -- Caddy will serve the necessary HTML+JS, and will proxy all requests to `/ws` to `biz:8443` over the internal docker network.

**Comment by masatrio-business-account** [comment]
Thanks a lot @leewardbound 
But how about listen port for biz?
can i change the port to 80 instead port 8443?

and how about SFU server? i read in WIKI it must expose port 5000-5200/udp,

please your help, thanks a lot

**Comment by leewardbound** [comment]
Yes, you can change `biz` to 80 if you want, if you aren't using `ion-app-web`. Biz does not really serve a UI though so I don't know why you'd want it to be on 80; up to you.

Yes, sorry I forgot to mention that (large) detail - SFU also has to open UDP ports, 1-or-more per webrtc connection. You can specify the port range in the config; really you should try to make as many ports as possible available, 200 isn't very many for a large conference server. I'm experimenting myself with opening 50,000+ UDP ports but I don't think there's any official documentation around this.

**Comment by masatrio-business-account** [comment]
allright thanks a lot @leewardbound 

can i create 3 instance of each services ( biz, islb, sfu, avp ) ?

**Comment by masatrio-business-account** [comment]
Hi @leewardbound 
Is SFU needs an outside ports or just open udp ports internally?

**Comment by tarrencev** [comment]
UDP ports need to be open externally to establish webrtc transport

**Comment by leewardbound** [comment]
@masatrio-business-account The plan is to support multiple of each service, but currently behavior for multiples of each instances isn't well defined; it is still very WIP and unsupported.

**Comment by masatrio-business-account** [comment]
thanks guys @tarrencev @leewardbound 

whats avp?

why avp need - "./:/out/" volume in docker compose?

**Comment by tarrencev** [comment]
avp is for audio/video processing. the mounted directory is for outputting recordings

**Comment by masatrio-business-account** [comment]
is there any extra configuration if i deploy ion-web-app and ion-backend in separate domain?

please help, thanks

**Comment by masatrio-business-account** [comment]
can you guys guide me to deploy this service separately? 
i need this to deploy it for education startup in indonesia, thanks a lot

**Comment by leewardbound** [comment]
Sorry, this use case is not currently supported. It might be possible, but
we aren't completely sure, and we can't really help you through this.

Also, we should close this ticket. This ticking system is primarily for bug
reports and tracking issues, rather than support tickets -- since it seems
like you need a lot of assistance, you might find someone kind enough to
help in #pion on the Golang Gophers slack chat, there's a link on the
project page to join -- but our project is run by a community of
volunteers, so if you wind up getting that working, you should write a
guide for our docs!
