### ISSUE TITLE
Not found any node for islb

### ISSUE THREAD

**Issue by rajababu3** [ionorg/ion#305]
```
DEBUG: Recivied data: {"response":true,"id":2462221,"ok":false,"errorCode":500,"errorReason":"Not found any node for islb."}
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: {code: 500, error: Not found any node for islb.}
```

I am getting the above error after 2 or 3 days of the server running. 
To fix this again I have to do docker-compose up.

**Comment by adwpc** [comment]
this error occur again. maybe you can find error in biz and islb log

**Comment by rajababu3** [comment]
Okay. How can I fix this issue? I am using v0.4.6

**Comment by tarrencev** [comment]
What platform are you running the node on?

**Comment by rajababu3** [comment]
Digital Ocean (Docker)

**Comment by masatrio-business-account** [comment]
yes, same issue here, I have to re composed to fix this

**Comment by adwpc** [comment]
Please take a look at your cpu usage when error occur

**Comment by rajababu3** [comment]
Okay, Thank you, I will do that and share a pic. I am using a $20 plan on the digital ocean for testing and I got this error during testing like only 2 peers where connected on the call.

 Any suggestion like 4GB | 2vCPUs can handle how many users at a time?

**Comment by billylindeman** [comment]
Ran into this and I'm curious if this is the culprit https://github.com/cloudwebrtc/nats-protoo/blob/master/protoo.go#L49   

When the nats connection dies, a "close" event is emitted on nats-protoo that doesn't seem to be handled in the node process

**Comment by ganadevprajapathy** [comment]
+1.  At times, "Service node [sfu] not found" errors are encountered. Had to docker-compose up again to rectify. Need fix for this. Raises reliability issues. Any idea on how I can handle them apart from re composing docker? (I use digitalocean for hosting the server.)
