### ISSUE TITLE
Helm support

### ISSUE THREAD

**Issue by m9rc1n** [ionorg/ion#313]
Hi guys,
You've done a great job with this project! Amazing work.

Are you planning to add Helm? If so, I could help you to organize the charts.

Btw. did you manage to run v0.4.6 with Kubernetes?
Every time one joins a session, then "stream removed" event appears after few seconds. It works fine with docker-compose (locally). I had my cluster running on Digital Ocean.

**Comment by tarrencev** [comment]
@leewardbound is working on kube stuff. would be awesome to have helm charts!

**Comment by leewardbound** [comment]
Yes please! I mentioned in my README -- a Helm chart is a *definite* todo,
and I started to write one originally, but I've never built a helm chart
before and it was slowing me down so I scrapped it -- I welcome any PR you
want to send!

I am running 0.4.6 on my k8s cluster right now; stability isn't perfect but
better than you describe, I do not have "stream removed" events.

**Comment by billylindeman** [comment]
@maszhin I've got a helm chart for v0.4.6 I can contribute that I wrote last week!  We've been running it in GKE and it works.  I'll put together a WIP pull request for it this afternoon

**Comment by m9rc1n** [comment]
Thanks guys. It can be Digital Ocean issue. 
I will try on GKE.
