### ISSUE TITLE
Support Protobuf and Schema Evolution

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#39]
My understanding is that ION is essentially a custom Transport.

At the moment its designed to transport JSON.

JSON however has the problem in that it does not support Scheme Evolution.
For example, if a dev changed the Data Schema of a type that is shared between the client and the server then the client will "crash" as it will not be able to understand the payload.

Schema Evolution using Protobufs solves this because the Fields are numbered and the generated Protobufs for the Client and Server respect that field numbering in order to ignore fields it does not understand in the payload without "crashing".

So i am raising the Idea for ION to use Protobufs and not JSON so that its more resilient to natural development cycles and is more Production ready.

---

As a side note:
I am also pointing out that Code generation of the Client code (Dart and JS ) and the Server code ( Golang) from  the Protobufs is possible, BUT i dont think its easy to do with the custom transport. 
Maybe it is but i fear it will essentally be a rewrite of:
- envoy
- grpc-gateway

**Comment by winwisely99** [comment]
We dont need this now. we got GRPC-Web working.

So you can close if you dont need it.

**Comment by cloudwebrtc** [comment]
@winwisely99 Use GRPC-Web to connect nodes between services?
