### ISSUE TITLE
Flutter Client

### ISSUE THREAD

**Issue by ghost** [ionorg/ion#4]
Its good to have a standard Dart client For Flutter, but also i would support a gomobile based one too.

The gomobile client is wrapped by a standard Flutter Plugin, but it allows oyu to have golang for the client and server and that can mean less techncial debt and less bugs. Its quite difficult to get a Pub SUb system to be sturdy over changing network conditions and other aspects i my option

**Comment by cloudwebrtc** [comment]
The [Flutter Client SDK](https://github.com/cloudwebrtc/pion-sfu/tree/flutter_sdk/sdk/flutter) will be merged after development.

**Comment by cloudwebrtc** [comment]
<img width="200" height="360" src="https://user-images.githubusercontent.com/17733746/58677074-28399300-838d-11e9-87e0-c019bda6d322.png"/>

**Comment by cloudwebrtc** [comment]
Flutter client support has been added.
