### ISSUE TITLE
Error authenticating user => no token

### ISSUE THREAD

**Issue by linuxtmty** [ionorg/ion#421]
used the latest ion, ion app web, but when I click test connection on the login page, the server will appear: error authenticating user = > no token. What's wrong with this?

**Comment by buriedgod** [comment]
I had the same issue ( i tried with docker-compose), the issue is with the docker-compose.yml in the ion (backend), using docker-compose.stable.yml fixed it for me.

Example usage: docker-compose -f docker-compose.stable.yml up
