### ISSUE TITLE
Flutter Web WebRTC running on Desktop ( using ASTI ) and Notifications

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#44]
We knwo that ASTI works. YEAH :)

But how to do local notifications then if the Client is not open ?

On the Desktop run a Golang Proxy ( as a desktop Service) that is always on, so that notifications can be raised. Even if the Client is closed.

The Golang Proxy talks to the Cloud backend using pure GRPC ( for ION however it does it ). Thats easy.
- So the Golang Proxy needs to be able to send data to the Asti Flutter Web.
- It can do this by raising a Desktop Notification, and then when the user clicks on it the URL Schema ( declared by the ASTI Client App)  will cause the Client to open on the correct page ( aka Flutter Routing).

---

Code notes.

This provides the URL Schemes and Deep Links support.
https://pub.dev/packages/uni_links
-  Says it works with flutter web ? We need to try this with our ASI based demo.

This allows Local Notifications on IOS and Android BTW:
https://github.com/MaikuB/flutter_local_notifications
- Looks very clean
- Example app using it: https://github.com/yass0016/nextmed/blob/master/pubspec.yaml#L16
 - might need special permissions so can see them here.

---

If the ASTI Flutter Web wants to communicate with the Cloud GRPC ( and ION Cloud)  its just standard stuff.

**Comment by adwpc** [comment]
Flutter sdk moved to:
https://github.com/pion/ion-sdk-flutter
Please make issue there
