### ISSUE TITLE
Remove Travis-CI setting or contact Travis-CI to enable OSS credits

### ISSUE THREAD

**Issue by at-wat** [ionorg/ion#442]
Travis-CI recently disabled free OSS build by default.
https://docs.travis-ci.com/user/billing-overview/#credits-vs-oss-only-credits
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

Currently, pion organization exceeds the free plan credits and CI on Travis is stopped.
![image](https://user-images.githubusercontent.com/8390204/100709216-0d683480-33f1-11eb-8ac7-ee08e687f081.png)

Credits | OSS only credits
--- | ---
![image](https://user-images.githubusercontent.com/8390204/100709118-e01b8680-33f0-11eb-9fc1-1e51e10641ce.png) | ![image](https://user-images.githubusercontent.com/8390204/100709265-1d801400-33f1-11eb-9e6a-8e487fe51bd1.png)

Please consider migrating it to GitHub Actions or contact Travis CI staff to enable OSS credits.
(I think `ion` is the last active repository using Travis-CI in pion org.)

**Comment by cgojin** [comment]
removed it.
