### ISSUE TITLE
Flutter Web WebRTC running on Mobile

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#45]
It would be useful for some use cases if WebRTC can run on Mobiles as a Flutter Web.
- Allows decoupled application to be built.
- Instant updates
- Sucky perf though, but Flutter Web compiler is getting better and better.
- Sandboxed security and easier for certain Orgs to use.
- No Need to sign code.

It seems that the WebView on Mobile  does NOT give access to the required APIS.
- SO that rules out using Flutter WebView plugin.

1. Try out the Flutter Web Webrtc on your IOS device in a browser.
- Does it work ?

So what about as a PWA then.
- PWA on IOS i have not used. 
- PWA on Android i have used and google are usign it too. E.g Google Travel and Google Drive so far
- It maybe that a PWA on Mobile is using A WebView but its has the rights to do WebRTC !
- Flutter Web does compile as a PWA. No problem there.

What about NOT as a PWA ?
- Does Flutter Web version run in a browser on Mobile ?

What about Local notifications ?
- BUT, it will mean that some things like Local Notifications wont work IF the App is NOT open ?

**Comment by adwpc** [comment]
Flutter sdk moved to:
https://github.com/pion/ion-sdk-flutter
Please make issue there
