### ISSUE TITLE
Cors Based Archi

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#46]
If we can use Flutter Web on Desktop and Mobile is means a few things

1. Sandboxed and trusted.
2. Instant updates
3. Perf will suck

But the main thing is that then you can build apps that are more like a CMS.
A Dev can make a Project that reuses Flutter Web WebRTC but does NOT compile against it.

Technically, It would mean that the Flutter Web would need to use CORS to declare that Servers it allows. Standard internet security.

See here for background: https://github.com/flutter/flutter/issues/46904

**Comment by adwpc** [comment]
Flutter sdk moved to:
https://github.com/pion/ion-sdk-flutter
Please make issue there if you want
