### ISSUE TITLE
[Question] Deploy ion with web frontend with docker 

### ISSUE THREAD

**Issue by pwFoo** [ionorg/ion#467]
Hi,

I would try to test ion self hosted. Here is a docker compose file  in ion project. Looks like just backend / server part?
Also found https://github.com/pion/ion-app-web. 

A online demo and a complete compose with to deploy the server and client side with some instructions would be great!

**Comment by pwFoo** [comment]
I would try to deploy ion with docker swarm compose file including a web frontend. At the moment build custom images, host dir mappings and config files are needed. So project can't be deployed as simple as nextcloud or jitsi?

**Comment by oren** [comment]
I am new to webrtc and interested to test ion. are there clear instructions of how to set it up on my laptop and allowing a few friends to join (on a different network, not from my home)?

I run the quickstart but had no idea how to test things. Thank you!
