### ISSUE TITLE
Dependency failure @master and latest 1.5.3🏷 

### ISSUE THREAD

**Issue by paalgyula** [ionorg/ion#472]
### Your environment.
  - Version: *#v1.5.3@f3431854*

### What did you do?
```bash
❯ go mod download
go: github.com/pion/webrtc/v3@v3.0.0-beta.12.0.20201115002753-64bbf7eea97d: invalid version: unknown revision 64bbf7eea97d
```

### What did you expect?
Pull and build/compile the project

### What happened?
I've checked out the project and switched to the latest tag and the dependency is missing.
Also I've tried to override the dependency to 3.0.0-beta.12 but there's a braking change

**Comment by adwpc** [comment]
A better version will come.
