### ISSUE TITLE
nil panic in biz handle

### ISSUE THREAD

**Issue by funvit** [ionorg/ion#481]
### Your environment.
  - Version: v1.5.3
  - Browser: no
  - Other Information : stack trace

```
ion_biz  | panic: runtime error: invalid memory address or nil pointer dereference
ion_biz  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xb660a5]
ion_biz  | 
ion_biz  | goroutine 31 [running]:
ion_biz  | github.com/pion/ion/pkg/node/biz.(*peer).Handle(0xc000122300, 0xf7e880, 0xc0005168c0, 0xc0003c62d0, 0xc0000d9310)
ion_biz  | 	/go/src/github.com/pion/ion/pkg/node/biz/peer.go:62 +0x145
ion_biz  | github.com/sourcegraph/jsonrpc2.(*Conn).readMessages(0xc0003c62d0, 0xf7e880, 0xc0005168c0)
ion_biz  | 	/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20200429184054-15c2290dcb37/jsonrpc2.go:522 +0x567
ion_biz  | created by github.com/sourcegraph/jsonrpc2.NewConn
ion_biz  | 	/go/pkg/mod/github.com/sourcegraph/jsonrpc2@v0.0.0-20200429184054-15c2290dcb37/jsonrpc2.go:334 +0x1cc
```

### What did you do?

Trying simple connect to biz port and send JoinCmd (from golang client code).

### What did you expect?

Answer from server.

### What happened?

1. No answer from server.
2. Nil panic in logs.

---

Looks like `req.Params` can be nil ([see here]( https://github.com/sourcegraph/jsonrpc2/blob/366fbb52075002042e4537caed004f27fa463174/jsonrpc2.go#L92)) , so nil-check must be implemented.

**Comment by adwpc** [comment]
new vision will come.
