### ISSUE TITLE
How to identify who the stream belongs to？

### ISSUE THREAD

**Issue by ChenSino** [ionorg/ion#503]
I wan't to show the user name（remote user）  on the video ,but I don't know how to identify who the stream belongs to in the ontrack event .Is there any way to pass a param when publish the stream ,and get the param in the ontrack event?
Help please，Thanks in advance！

![image](https://user-images.githubusercontent.com/25560521/112265291-3a489c00-8cad-11eb-9a4c-f305e9121648.png)

**Comment by adwpc** [comment]
see ion-app-web, support user name
