### ISSUE TITLE
When both devices are on same wifi does not work sometimes

### ISSUE THREAD

**Issue by winwisely99** [ionorg/ion#51]
During a demo 2 devices were on wifi and neither showed up in the list.
Even SELF did not show up.
This was in a corporate network
I assume it was because the router was a symmetric router ?
We were running off the current CloudWebrtc gateway server.
How to mitigate this ?

**Comment by adwpc** [comment]
fixed in nats-mq branch

**Comment by adwpc** [comment]
nats-mq now merged to master
