### ISSUE TITLE
Websocket issue in Echotest

### ISSUE THREAD

**Issue by fenestron** [ionorg/ion#517]
### Your environment.
  - Version: *ffca46a215387612cfe93f9952fe218a5105a7f5*
  - Browser: *Google Chrome 89.0.4389.90*

### What did you do?

1. Cloned the repository:
`git clone https://github.com/pion/ion && cd ion`

2. Added `echotest` to `services` in `docker-compose.yml` file:
```
  echotest:
    image: nginx
    volumes:
      - ./examples/echotest/:/usr/share/nginx/html
    ports:
      - 8080:80
```

3. Run:
`docker-compose up --build`

4. Open browser and go to localhost:
`http://localhost:8080/`

### What did you expect?

Working `echotest` example

### What happened?
I get an error:
`WebSocket connection to 'ws://localhost:8443/ws?uid=7a2cd0c4-3304-4eef-a105-51696b0dad53' failed: `

![image](https://user-images.githubusercontent.com/9680621/112882800-18e51700-90d6-11eb-8eac-cb103530478f.png)

### Additional Information

The line in the code:
https://github.com/pion/ion/blob/ffca46a215387612cfe93f9952fe218a5105a7f5/examples/echotest/index.html#L369

The `biz` service began to use port `5551` instead of `8443`:
https://github.com/pion/ion/blob/ffca46a215387612cfe93f9952fe218a5105a7f5/docker-compose.yml#L55

There was a similar error before and it was fixed by replacing `uid` with `peer`. Related commit:
https://github.com/pion/ion/pull/466/commits/b0f685aa62a14978ae2f9acb9e2a9fc0226b0acf

Replacing the strings did not solve the problem:
`ws://localhost:8443/ws?uid=` with `ws://localhost:5551/ws?peer=`

---
What could be the problem and how to solve it?

**Comment by cloudwebrtc** [comment]
Hey, this `ion/examples/echotest/index.html` example can only run on 0.4.6, 
you can use the new example to connect to ion
https://github.com/pion/ion/tree/ion-js-example/examples/pubsubtest

We are actively making other examples

**Comment by fenestron** [comment]
Thank you so much! That's what I need.
Looking forward to more examples.
