### ISSUE TITLE
AVP does not start recording

### ISSUE THREAD

**Issue by fenestron** [ionorg/ion#524]
### Your environment.
  - Version: *ffca46a215387612cfe93f9952fe218a5105a7f5* and *17c29be32e3eefcb47618f69e50836528e3eb65d*
  - Browser: *Google Chrome 89.0.4389.90*

### What did you do?
1. Cloned the project and run docker-compose:
```
git clone https://github.com/pion/ion && cd ion
docker-compose up --build
```

2. Downloaded `pubsubtest` from `ion-js-example` branch (https://github.com/pion/ion/tree/ion-js-example/examples/pubsubtest)

3. Ran `pubsubtest` with another docker-compose file:
```
version: "3.7"

services:
  pubsub:
    image: nginx
    volumes:
      - ./examples/pubsubtest/:/usr/share/nginx/html
    ports:
      - 8080:80
```

4. Launched the browser and switched to http://localhost:8080/ in 2 tabs

5. Clicked the `start` button on each tab

### What did you expect?

Recording of each stream in webm format in the `out` folder

### What happened?
The `out` folder was created in the root of the project 

The `out` folder was empty

### Additional Information

All mentions of `AVP` in the log:
```
avp_1    | config /configs/avp.toml load ok!
avp_1    | [2021-03-31 09:03:25.830] [INFO] [83][main.go][main] => --- starting avp node ---
avp_1    | [2021-03-31 09:03:25.830] [INFO] [62][avp.go][func1] => start pprof on :6063
avp_1    | time="2021-03-31T09:03:25Z" level=info msg="QueueSubscribe: subject => nrpc.avp.avp.AVP.>, queue => avp.AVP" sid=avp
avp_1    | time="2021-03-31T09:03:25Z" level=info msg="RegisterService: stream path => nrpc.avp.avp.AVP.Signal" sid=avp
avp_1    | [2021-03-31 09:03:25.831] [INFO] [70][node.go][Watch] => Get: subj=node.publish.islb
avp_1    | [2021-03-31 09:03:25.832] [INFO] [70][node.go][Watch] => nodes [{dc1 islb islb00 {nats-grpc nats://nats:4222 map[]} map[]}]
avp_1    | [2021-03-31 09:03:25.832] [INFO] [76][node.go][Watch] => Service up: islb node id => [islb00], rpc => nats-grpc
```

Full log - [log.txt](https://github.com/pion/ion/files/6235368/log.txt)

This behavior is observed after an upgrade. On version 1.5.1, files were created.

---

Please tell me why this is happening and how to fix it?

**Comment by nntwelve** [comment]
did you fix it bro??

**Comment by adwpc** [comment]
avp should rewrite with ion-sdk-go in new version
