### ISSUE TITLE
flutter_webrtc ^0.2.7 which doesn't match any versions, version solving failed.

### ISSUE THREAD

**Issue by jonahzheng** [ionorg/ion#55]
### What did you do?
cd ./ion/sdk/flutter/example
flutter pub get

### What happened?

Because flutter_ion depends on flutter_webrtc ^0.2.7 which doesn't match any versions, version solving failed.
Running "flutter pub get" in flutter...                                 
pub get failed (1; Because flutter_ion depends on flutter_webrtc ^0.2.7 which doesn't match any versions, version solving failed.)

**Comment by cloudwebrtc** [comment]
@jonahzheng I guess you use the storage.flutter-io.cn mirror to download plugins in China by default. I also do n’t know why. You can see 0.2.7 in the list of this mirror, but you ca n’t download it, I switched to another mirror and it downloads normally

You can try another mirror:
```bash
export PUB_HOSTED_URL = http: //mirrors.cnnic.cn/dart-pub
export FLUTTER_STORAGE_BASE_URL = http: //mirrors.cnnic.cn/flutter
```

**Comment by jonahzheng** [comment]
yes, my guess would be cache.
switched to mirror, the problem is solved,
@cloudwebrtc thank you, good job!
