### ISSUE TITLE
panic: send on closed channel

### ISSUE THREAD

**Issue by venffet** [ionorg/ion#555]
### Your environment.
  - Version: *62cb04f*

### What happened?
sfu server throw exception and shutdown  

panic: send on closed channel

goroutine 19 [running]:
github.com/nats-io/nats%2ego.(*Conn).processMsg(0xc00033e000, 0xc00024e054, 0x2, 0x7fac)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2294 +0x5b7
github.com/nats-io/nats%2ego.(*Conn).parse(0xc00033e000, 0xc00024e000, 0x58, 0x8000, 0x58, 0x0)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/parser.go:177 +0xb25
github.com/nats-io/nats%2ego.(*Conn).readLoop(0xc00033e000)
        /go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:2147 +0x176
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
        /go/pkg/mod/github.com/nats-io/nats.go@v1.10.0/nats.go:1489 +0x1a7

**Comment by thaidh** [comment]
i have same issue on biz node

panic: send on closed channel

goroutine 10 [running]:
github.com/nats-io/nats%2ego.(*Conn).processMsg(0xc000204600, 0xc000234058, 0x2, 0x7fa8)
	/go/pkg/mod/github.com/nats-io/nats.go@v1.11.0/nats.go:2673 +0x80a
github.com/nats-io/nats%2ego.(*Conn).parse(0xc000204600, 0xc000234000, 0x5c, 0x8000, 0x0, 0x0)
	/go/pkg/mod/github.com/nats-io/nats.go@v1.11.0/parser.go:192 +0xb9c
github.com/nats-io/nats%2ego.(*Conn).readLoop(0xc000204600)
	/go/pkg/mod/github.com/nats-io/nats.go@v1.11.0/nats.go:2485 +0x16b
created by github.com/nats-io/nats%2ego.(*Conn).processConnectInit
	/go/pkg/mod/github.com/nats-io/nats.go@v1.11.0/nats.go:1851 +0x1a7

**Comment by adwpc** [comment]
@thaidh seems nats issue, updated nats package.
