### ISSUE TITLE
RTCPeerConnection addTransceiver method not found

### ISSUE THREAD

**Issue by Faiyyaz** [ionorg/ion#56]
### Your environment.
  - Version: iOS
  - Browser: Safari
  - Other Information - ```error: The method 'addTransceiver' isn't defined for the class 'RTCPeerConnection'. (undefined_method at [brodacaster] lib/src/client.dart:216)```

### What did you do?
I just cloned the repo and tried running example on iOS simulator

### What did you expect?
I expect it to at least build successfully

### What happened?
It gives me error on building and i am unable to install

**Comment by Faiyyaz** [comment]
Hi,

Thanks for the update

But we are facing an issue while calling in a room

If we connect together we are unable to see each other but we can see ourself & the 1st person can hear the 2nd person.
If one of us disconnects then the video gets hanged up for other person but the person who has just joined can see the video properly and audio is also fine for the said person.

So basically there is a bug in room.

**Comment by cloudwebrtc** [comment]
@Faiyyaz Hey, We have updated the repo, the problem may be caused by https://github.com/pion/webrtc/issues/1081, The sdk has been temporarily fixed and you can try again.

**Comment by jonahzheng** [comment]
@Faiyyaz @cloudwebrtc this same issue, in a room can't see each other.

**Comment by Faiyyaz** [comment]
@cloudwebrtc Will test and let you know the result.

Also wanted to ask you one thing  is it recommended to use this in production environment?

**Comment by Faiyyaz** [comment]
I tested the build i found only one issue that in iOS incoming voice is coming very low because the sound is coming from phone speaker rather than loud speaker.

Even the bug still persists on iOS

**Comment by cloudwebrtc** [comment]
@Faiyyaz I have created a new issue and will fix it.
https://github.com/pion/ion/issues/65

**Comment by cloudwebrtc** [comment]
> Also wanted to ask you one thing is it recommended to use this in production environment?

ion is a booming project, and many people @Sean-Der @adwpc  are currently working on it. I believe it will become a product-level solution in a short period of time.

**Comment by Sean-Der** [comment]
@Faiyyaz I plan on working on `pion/ion` until it is perfect!

I think the biggest difference with Pion is that you don't have a single point of failure. With many other Open Source projects you have a single person that drives everything. If you look at any of the repos under the Pion organization you will see a diverse range of contributors.

Maybe we don't have a certain feature today, but you can't beat the community we are building long term :)

**Comment by Faiyyaz** [comment]
Ok thanks for the help.

Yes, it is a good library and i would be happy to see it stable someday

**Comment by Sean-Der** [comment]
Thanks for using Pion @Faiyyaz :) We really appreciate all the bug reports, and people using it means a lot to us

**Comment by Faiyyaz** [comment]
Hey,

Is this currently stable for production or should you advise not to use it now also?
