### ISSUE TITLE
Can't see remote video

### ISSUE THREAD

**Issue by skiffer-git** [ionorg/ion#576]
### Your environment.
![733db419bcc7a5bfd9349a173992587](https://user-images.githubusercontent.com/72860476/127725097-655fb95e-67ee-4ea3-8983-c583a70c53d2.jpg)
[3](https://user-images.githubusercontent.com/72860476/127725115-db4c167d-b4f3-4790-be1c-8650e80d8a5c.png)
### What did you do?
I QUICKSTART form docker 
client demo is  ion-app-flutter— flutter application

### What happened?
root peers is 2, but I can't see remote video ![3](https://user-images.githubusercontent.com/72860476/127725115-db4c167d-b4f3-4790-be1c-8650e80d8a5c.png)

**Comment by smc181002** [comment]
go into your configs/docker/sfu.toml file and uncomment nat1to1 line and the icelite line.
```
nat1to1 = ["xxx.xxx.xxx.xxx"]
icelite = true
```
also, check for firewall rules in your remote server
the docs were updated recently
https://pionion.github.io/deploy/docker/

**Comment by gr8den** [comment]
> go into your configs/docker/sfu.toml file and uncomment nat1to1 line and the icelite line.
> 
> ```
> nat1to1 = ["xxx.xxx.xxx.xxx"]
> icelite = true
> ```
> 
> also, check for firewall rules in your remote server the docs were updated recently https://pionion.github.io/deploy/docker/

I try configure this options but still have same problem. Participants can join to room, but media streams not working
