### ISSUE TITLE
nats: no servers available for connection

### ISSUE THREAD

**Issue by wzrf** [ionorg/ion#579]
Hi, I have problem starting the docker services. When I try to launch the services, it gives me
Starting ion_nats_1  ... done
Starting ion_redis_1 ... done
Recreating ion_islb_1 ... done
Recreating ion_app-biz_1 ... done
Recreating ion_sfu_1     ... done
Recreating ion_signal_1  ... done
Attaching to ion_nats_1, ion_redis_1, ion_islb_1, ion_sfu_1, ion_app-biz_1, ion_signal_1
redis_1    | 1:C 14 Aug 2021 12:25:43.980 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
redis_1    | 1:C 14 Aug 2021 12:25:43.980 # Redis version=6.0.9, bits=64, commit=00000000, modified=0, pid=1, just started
redis_1    | 1:C 14 Aug 2021 12:25:43.980 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
nats_1     | [1] 2021/08/14 12:25:43.786132 [INF] Starting nats-server
nats_1     | [1] 2021/08/14 12:25:43.786168 [INF]   Version:  2.3.4
nats_1     | [1] 2021/08/14 12:25:43.786171 [INF]   Git:      [7112ae0]
nats_1     | [1] 2021/08/14 12:25:43.786175 [INF]   Name:     NBQDXCNWUH2MMTGLLR5IGU34RD3ZOVRBMK3DYVW3PU2AVLUHDWFSBQSJ
nats_1     | [1] 2021/08/14 12:25:43.786181 [INF]   ID:       NBQDXCNWUH2MMTGLLR5IGU34RD3ZOVRBMK3DYVW3PU2AVLUHDWFSBQSJ
nats_1     | [1] 2021/08/14 12:25:43.786186 [INF] Using configuration file: nats-server.conf
islb_1     | config /configs/islb.toml load ok!
islb_1     | time="2021-08-14 12:25:44.468" msg="--- starting islb node ---"
islb_1     | time="2021-08-14 12:25:44.468" msg="start pprof on :6061"
islb_1     | time="2021-08-14 12:25:44.469" msg="new nats conn error nats: no servers available for connection"
islb_1     | time="2021-08-14 12:25:44.469" msg="islb start error: nats: no servers available for connection"
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * Running mode=standalone, port=6379.
redis_1    | 1:M 14 Aug 2021 12:25:43.981 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/somaxconn is set to the lower value of 128.
redis_1    | 1:M 14 Aug 2021 12:25:43.981 # Server initialized
redis_1    | 1:M 14 Aug 2021 12:25:43.981 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
sfu_1      | config /configs/sfu.toml load ok!
nats_1     | [1] 2021/08/14 12:25:43.787187 [INF] Starting http monitor on 0.0.0.0:8222
sfu_1      | time="2021-08-14 12:25:45.528" msg="--- starting sfu node ---"
sfu_1      | time="2021-08-14 12:25:45.528" msg="start pprof on :6062"
nats_1     | [1] 2021/08/14 12:25:43.787241 [INF] Listening for client connections on 0.0.0.0:4222
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * Loading RDB produced by version 6.0.9
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * RDB age 6 seconds
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * RDB memory usage when created 0.77 Mb
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * DB loaded from disk: 0.000 seconds
redis_1    | 1:M 14 Aug 2021 12:25:43.981 * Ready to accept connections
sfu_1      | time="2021-08-14 12:25:45.531" msg="new nats conn error nats: no servers available for connection"
sfu_1      | time="2021-08-14 12:25:45.531" msg="sfu init start: nats: no servers available for connection"
signal_1   | config /configs/signal.toml load ok!
signal_1   | time="2021-08-14 12:25:47.128" msg="--- Starting Signal (gRPC + gRPC-Web) Server ---"
signal_1   | time="2021-08-14 12:25:47.128" msg="--- Bind to 0.0.0.0:5551, NID = sig01 ---"
signal_1   | time="2021-08-14 12:25:47.129" msg="new nats conn error nats: no servers available for connection"
signal_1   | time="2021-08-14 12:25:47.129" msg="new signal: nats: no servers available for connection"
nats_1     | [1] 2021/08/14 12:25:43.787652 [INF] Server is ready
ion_islb_1 exited with code 255
nats_1     | [1] 2021/08/14 12:25:43.787675 [INF] Cluster name is oFGqGnOCPjNueMxldiybHE
nats_1     | [1] 2021/08/14 12:25:43.787678 [WRN] Cluster name was dynamically generated, consider setting one
nats_1     | [1] 2021/08/14 12:25:43.787700 [INF] Listening for route connections on 0.0.0.0:6222
app-biz_1  | config /configs/app-biz.toml load ok!
app-biz_1  | time="2021-08-14 12:25:45.633" msg="--- [mengyao_debug] Starting Biz Node ---"
ion_sfu_1 exited with code 255
app-biz_1  | time="2021-08-14 12:25:45.633" msg="start pprof on :6060"
app-biz_1  | time="2021-08-14 12:25:45.635" msg="new nats conn error nats: no servers available for connection"
app-biz_1  | time="2021-08-14 12:25:45.635" msg="nats: no servers available for connection"
app-biz_1  | time="2021-08-14 12:25:45.635" msg="nats://nats:4222"
app-biz_1  | panic: runtime error: invalid memory address or nil pointer dereference
app-biz_1  | [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x9ec88d]

It seems that it cannot connect to nats:4222, while that the nat docker is already started, and 4222 port is opened.

**Comment by adwpc** [comment]
please try new version
