### ISSUE TITLE
Docker/deploy improvements 

### ISSUE THREAD

**Issue by Sean-Der** [ionorg/ion#62]
I am just dropping a list of ideas/improvements. If some of these don't make sense please push back! There is a big demand for conference software happening. If we can make ion the easiest SFU to deploy (and the most perfomant) this could be really great for the project :)

When these are solved I will post on Reddit/HN/Twitter and we will see a great response.

### Use LetsEncrypt 
When everything comes up we should make cert generation easier.

### Host pre-made images in Dockerhub (done)
Users shouldn't have to build anything locally. We should continue to make local development easy though!

### Use SetNAT1To1IPs 
Pion supports setting your Public IP in the config. We need to do this because the service is running in a container (and does not know the host IP). We can script this so a user doesn't even have to do anything, we will just autoset this on startup by using a service like 'whatismyip'.

### Use SetEphemeralUDPPortRange (done)
Since ion doesn't have access to any of the hosts interfaces it can't get any inbound traffic. We should expose a range of UDP ports, and then use SetEphemeralUDPPortRange to make sure `pion/ion` only listens on the range that are exposed by the host operating system.

**Comment by adwpc** [comment]
100% agree！
I can do `SetEphemeralUDPPortRange `, now i need a best port range

**Comment by adwpc** [comment]
Should I close this？

**Comment by Sean-Der** [comment]
Sorry forgot to close! I will keep working on deploy improvements to make it easier, I think it will get a lot more people pulled in the easier it gets.

I think Heroku/DigitalOcean have stuff that can auto-deploy just from a URL, will look into it.

**Comment by adwpc** [comment]
Thanks，and the web container is too big
