### ISSUE TITLE
Add pre-made flutter app

### ISSUE THREAD

**Issue by cloudwebrtc** [ionorg/ion#68]
About the native client of `Android/iOS/macOS/Web`, 
We can use Google Flutter to build a native client outside the browser, which will allow the mobile/desktop to perfectly connect to the ion.

- In the early stage, we can pre-compile APK or IPA using [CodeMagic](https://codemagic.io/)?
- When we have the official ion service, we can upload the app to App Store and GooglePlay,

(`Linux`, `Windows`, `Fuchsia` will be supported in the future)

**Comment by adwpc** [comment]
moved to:
https://github.com/pion/ion-sdk-flutter/issues/1
