### ISSUE TITLE
Public demo

### ISSUE THREAD

**Issue by Sean-Der** [ionorg/ion#69]
We should run a server so people can have a public demo. We will probably need to write some code that limits session lengths/amount of people on the server.

**Comment by jonahzheng** [comment]
yes, it will demonstrate the features of ion, in order to better understand ion.

**Comment by jonahzheng** [comment]
I have one simple question:what it means by 'islb,biz'?

**Comment by schors** [comment]
I need a more detailed info about biz architecture. It may be not formal. I quickly reviewed biz code. I think that it is right place for simple limitations. Am I right? I can try. It will greatly reduce a development time if you will explain biz architecture

**Comment by j4qfrost** [comment]
I'm trying to figure out how to use the biz nodes to grab video frames. is that possible? I am making an assumption that the biz node sets up a direct rpc connection between the external service and ion when the watcher receives a broadcast signal, but looking at cloudwebrtc's prooto code, that doesn't seem to be the case. Help?

**Comment by jzvi12** [comment]
Let me know guys if you need my Linux VPS to host this public demo =)
