### ISSUE TITLE
docker-compose up fails with permission error

### ISSUE THREAD

**Issue by DanielHeath** [ionorg/ion#73]
### What did you do?

```
  $ git rev-parse HEAD
6de4b0a01e40e08af827ac7292e3fae5ea0f3954

  $ docker --version
Docker version 18.09.9, build 1752eb3

  $ uname -a
Linux drh-workstation 5.3.0-40-generic #32-Ubuntu SMP Fri Jan 31 20:24:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

  $ sudo WWW_URL=video.nerdy.party ADMIN_EMAIL=daniel@heath.cc docker-compose up
Creating ion_etcd_1  ... error
Creating ion_nats_1 ... 
Creating ion_redis_1 ... 

Creating ion_nats_1  ... error
b72e2fb677369f816e0846d2f77b4622ab36cd363feb819894be3d7b88c5ee20-init/merged/etc/resolv.conf: permission denied

ERROR: for ion_nats_1  Cannot create container for service nats: open /var/snap/docker/common/var-lib-docker/overlay2/Creating ion_redis_1 ... error

ERROR: for ion_redis_1  Cannot create container for service redis: open /var/snap/docker/common/var-lib-docker/overlay2/042ae91874de99c893bdf5171a03c78820277632eac7d8a6a4c29ecc6387f78d-init/merged/etc/hosts: permission denied

ERROR: for nats  Cannot create container for service nats: open /var/snap/docker/common/var-lib-docker/overlay2/5e6e25f18fd38a9f27f65ebb1dc6579b1a78b953a80e25b61b59d5ae6fffceae-init/merged/etc/resolv.conf: permission denied

ERROR: for redis  Cannot create container for service redis: open /var/snap/docker/common/var-lib-docker/overlay2/042ae91874de99c893bdf5171a03c78820277632eac7d8a6a4c29ecc6387f78d-init/merged/etc/hosts: permission denied

ERROR: for etcd  Cannot create container for service etcd: open /var/snap/docker/common/var-lib-docker/overlay2/b72e2fb677369f816e0846d2f77b4622ab36cd363feb819894be3d7b88c5ee20-init/merged/etc/resolv.conf: permission denied
ERROR: Encountered errors while bringing up the project.

```

### What did you expect?
I expected docker-compose to start

### What happened?
Something (presumably inside the containers, as docker-compose is running as root?) does not have access

**Comment by hcm007** [comment]
@DanielHeath  Could you please clone the master branch again because I ran the same command as you 
`sudo WWW_URL=video.nerdy.party ADMIN_EMAIL=daniel@heath.cc docker-compose up`

It works ok for me, @Sean-Der  changed image parts of  docker-compose.yml, so users won't need to build images when they want to run docker-compose. If you change the source code, you can uncomment the image build part in the docker-compose.yml in order to use customized images.

**Comment by DanielHeath** [comment]
Ahh, I installed docker from a snap and AppArmor is ruining my day. Will try the .deb.

**Comment by Sean-Der** [comment]
Sorry about the trouble you are having @DanielHeath! 

I think a FAQ could help a lot also! I would love to work on make the README more accessible to people new to the project. If you have any questions/feedback that would help make it easier for others I would love to hear :)
