### ISSUE TITLE
Caddy has obsoleted scripts/makeKey.sh

### ISSUE THREAD

**Issue by mappu** [ionorg/ion#74]
The `scripts/makeKey.sh` is mentioned in the README.md. Seems like it generates self-signed certificates, that were passed to nginx, but are no longer used as of commit c3afdec8cce50b4cc3ddc2905ec74bd710bb722b

I think it's safe to remove from README.md?

certainly it confused me while setting up an instance.

**Comment by adwpc** [comment]
Update README.md
