### ISSUE TITLE
TypeError: navigator.mediaDevices is undefined

### ISSUE THREAD

**Issue by easydo247** [ionorg/ion#77]
Linux Mint 19.3 "Tricia" - Cinnamon (64-bit)
Firefox 74.0

docker compose up
open localhost:8080
browser console says:

TypeError: navigator.mediaDevices is undefined on line 141 in index.js

it seems the app doesn't ask for mic and cam permissions

**Comment by cloudwebrtc** [comment]
It should be that firefox cannot call getUserMedia under non-https.
