### ISSUE TITLE
User authentication

### ISSUE THREAD

**Issue by maxnoe** [ionorg/ion#78]
## Summary

User authentication, internally and/or externally would be great, as meetings are often confidential.

- [ ] Internal Users
- [ ] LDAP
- [ ] Oauth2
- [ ] Kerberos
- [ ] JWT
- [ ] Others?

**Comment by adwpc** [comment]
JWT is a choice

**Comment by maxnoe** [comment]
Added

**Comment by adwpc** [comment]
If you can help do this，that would be asome！

**Comment by adwpc** [comment]
We can choose a better one from these options

**Comment by Sean-Der** [comment]
@adwpc would it be possible to make `pion/ion` flexible enough to have users plug in their own authentication?

Maybe we could have an 'authentication host', and the default one would just let everyone in? But then users could then do JWT/Kerberos etc.. if they wanted.

I don't have an opinion on which one we do, I just know if people have already picked an existing auth solution they will need to stick with it. So if we pick one then everyone else gets locked out :(

**Comment by adwpc** [comment]
@Sean-Der 
I have no idea about `flexible enough auth ` recently.
jwt is a choice
People can diy a websocket proxy with auth, this proxy is made for biz module, just disconnect when auth failed

**Comment by winwisely99** [comment]
Yeah flexible enough is really hard. JWT is a decent option for now, but i agree others will want more enterprise friendly ones later.

OPA is flexible Authz, but not Auth.
https://github.com/open-policy-agent

**Comment by winwisely99** [comment]
I think Dex from videos is the best way to support any AUTH 

https://github.com/dexidp/dex

**Comment by GQAdonis** [comment]
I am currently working on a JWT implementation with extensible user authentication, roles, and authorization logic by creating an alternative `biz` implementation with a set of interfaces that can run through NATS, redis, and etcd in the current architecture to support the addition of a user management microservice that can be added.  This would allow maximum flexibility in how user management and room security is introduced.

**Comment by adwpc** [comment]
Awsome！Is this another biz-room？ ：）

**Comment by adwpc** [comment]
Can you add a configuable version in jwt，we can use it to check the client sdk version and the sfu version，reduce panic

**Comment by rajababu3** [comment]
+1
