### ISSUE TITLE
Remote Video show blank/black screen Flutter

### ISSUE THREAD

**Issue by aliheader** [ionorg/ion#89]
Remote video stream show black screen when other peers connected the conference call. Currently, just using the demo Flutter sdk.

**Comment by adwpc** [comment]
#93 may fix this
I will merge when this merged
https://github.com/pion/webrtc/pull/1109

**Comment by jonahzheng** [comment]
#67  in android and chrome, the same situation.

**Comment by ali7234** [comment]
Still facing the same issue of remote stream between two android devices, and between android device and chrome.
