### ISSUE TITLE
Shared conference input box blank

### ISSUE THREAD

**Issue by 0x11-dev** [ionorg/ion#90]
### Your environment.
  - Version: 171eacd5b48ac8926d9e41461f93cd4c805c31de
  - Browser: "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.149 Safari/537.36"
  - Other Information - *stacktraces, related issues, suggestions how to fix, links for us to have context*

### What did you do?

Click "Shared conference" Button on the top of the confluence demo web app。 Input box in the dialog is blank.

### What did you expect?

Show the result of url to share.

### What happened?
![image](https://user-images.githubusercontent.com/7822875/77844442-7f8cd780-71d9-11ea-83f7-b5ddfcf286ba.png)

**Comment by moqmar** [comment]
Seems like in `App.jsx:103` there's `loginInfo: values` missing, which in turn probably also requires it to be added in lines 23 and 214.
