### ISSUE TITLE
js_helper.dart:1342 Uncaught TypeError: a.$1 is not a function

### ISSUE THREAD

**Issue by jonahzheng** [ionorg/ion#96]
pc chrome
flutter web
![20200330235118](https://user-images.githubusercontent.com/5125282/77933545-843cb300-72e1-11ea-88d6-fcc322386e4a.png)

**Comment by adwpc** [comment]
flutter sdk moved to 
https://github.com/pion/ion-sdk-flutter
if this issue still exist, please make issue there
