### ISSUE TITLE
HandShakeEception: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by JCKodel** [ionorg/ion#98]
### Your environment.
  - Version: master
  - Browser: none
  - Other Information:
```
I/flutter ( 5124): [Logger::Dart::WebSocket] DEBUG: connect https://192.168.15.10:8443/ws?peer=08b97ada-7430-4e95-95c2-ba786b688159, {}, null
I/flutter ( 5124): [Logger::Dart::WebSocket] ERROR: error HandshakeException: Handshake error in client (OS Error:
I/flutter ( 5124):      WRONG_VERSION_NUMBER(tls_record.cc:242))
I/flutter ( 5124): [protoo-client] DEBUG: emit "error" [currentAttempt:NoSuchMethodError: The getter 'closeCode' was called on null.
I/flutter ( 5124): Receiver: null
I/flutter ( 5124): Tried calling: closeCode]
```

### What did you do?
1) Cloned this repo on one Windows machine
2) Run the Flutter example project
3) Running as it, no image is broadcast between the devices (all I can see is my own cam, but join/leave messages pops up)
4) Decided to try to install server on an Ubuntu 18.04 machine via docker
5) When connecting, the exception with WRONG_VERSION_NUMBER is thrown on Flutter project.

### What did you expect?
To work

### What happened?
Exception HandshakeException.WRONG_VERSION_NUMBER

**Comment by DenisBogatirov** [comment]
Same

**Comment by adwpc** [comment]
Flutter sdk moved to:
https://github.com/pion/ion-sdk-flutter
Please make issue there
